# .railway.yml
services:
  web:
    image: node:18
    build:
      commands:
        - yarn install
        - yarn build
    start:
      command: yarn start
    environment:
      NODE_ENV: production
